//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public int employee_id { get; set; }
        public string surname { get; set; }
        public string first_name { get; set; }
        public Nullable<System.DateTime> employment_date { get; set; }
        public string PESEL { get; set; }
    
        public virtual lecturers lecturers { get; set; }
    }
}
