//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityInfo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class universityEntities : DbContext
    {
        public universityEntities()
            : base("name=universityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acad_positions> acad_positions { get; set; }
        public virtual DbSet<departments> departments { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<grades> grades { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<lecturers> lecturers { get; set; }
        public virtual DbSet<modules> modules { get; set; }
        public virtual DbSet<student_grades> student_grades { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<students_modules> students_modules { get; set; }
        public virtual DbSet<tuition_fees> tuition_fees { get; set; }
    }
}
